# Generated by Django 4.2.16 on 2024-12-03 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_like'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='like',
            name='created_on',
        ),
    ]
